// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCisvjUePWPgFr2BtrqIDNak-tGGmIiesY',
    appId: '1:53520677791:web:016e9e7ee5d4d42d5bdbaa',
    messagingSenderId: '53520677791',
    projectId: 'inspector-f0183',
    authDomain: 'inspector-f0183.firebaseapp.com',
    databaseURL: 'https://inspector-f0183-default-rtdb.firebaseio.com',
    storageBucket: 'inspector-f0183.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6oBvwVZBrn6VzwkgauV3P1FUYg0efHgU',
    appId: '1:53520677791:android:4ff39b1f29dc71095bdbaa',
    messagingSenderId: '53520677791',
    projectId: 'inspector-f0183',
    databaseURL: 'https://inspector-f0183-default-rtdb.firebaseio.com',
    storageBucket: 'inspector-f0183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGgCQsHmqFKn2kzdBb5TwzFVTZdyXu7cY',
    appId: '1:53520677791:ios:acf37607c512d6815bdbaa',
    messagingSenderId: '53520677791',
    projectId: 'inspector-f0183',
    databaseURL: 'https://inspector-f0183-default-rtdb.firebaseio.com',
    storageBucket: 'inspector-f0183.appspot.com',
    iosBundleId: 'com.example.inspector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGgCQsHmqFKn2kzdBb5TwzFVTZdyXu7cY',
    appId: '1:53520677791:ios:acf37607c512d6815bdbaa',
    messagingSenderId: '53520677791',
    projectId: 'inspector-f0183',
    databaseURL: 'https://inspector-f0183-default-rtdb.firebaseio.com',
    storageBucket: 'inspector-f0183.appspot.com',
    iosBundleId: 'com.example.inspector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCisvjUePWPgFr2BtrqIDNak-tGGmIiesY',
    appId: '1:53520677791:web:227988fed6d8ff175bdbaa',
    messagingSenderId: '53520677791',
    projectId: 'inspector-f0183',
    authDomain: 'inspector-f0183.firebaseapp.com',
    databaseURL: 'https://inspector-f0183-default-rtdb.firebaseio.com',
    storageBucket: 'inspector-f0183.appspot.com',
  );
}
